minimum_pre_commit_version: 1.21.0
repos:

# default checks provided by the pre-commit framework
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-symlinks
  - id: trailing-whitespace

# check Python source code linting with pylint
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.3.1
  hooks:
  - id: pylint

# check Python source code linting with flake8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
    - id: flake8

# check Python function docstrings with pydocstyle
- repo: https://github.com/PyCQA/pydocstyle
  rev: 5.0.2
  hooks:
  - id: pydocstyle


# check and re-format (if needed) Python code with black
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black

# reorder Python imports for all Python modules
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.9.0
  hooks:
  - id: reorder-python-imports