---
name: lab03
break: true
indent: 4
---

# GatorGrader configuration file

# Learn more about GatorGrader and its supported checks by visiting this web site:
# https://github.com/GatorEducator/gatorgrader

# Explanation:
# --> a check without an "--exact" runs a count for an entity as an "at least"
# --> checks below a file in a specified directory are for that specific file and directory
# --> checks that appear stand-alone are for an entire Git repository

# --> check the source code for various characteristics
src/generator.py:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 2
            #CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "Your Names" --count 0 --exact
src/analyzer.py:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 2
            #CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "Your Names" --count 0 --exact
# --> check the technical writing for various characteristics
writing/report.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 10 --exact
    #CountMarkdownTags --tag "code" --count 3 --exact
    CountMarkdownTags --tag "code_block" --count 1
    CountMarkdownTags --tag "list" --count 1
    MatchFileFragment --fragment "Your Names" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 10
